### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by jpwesselink** [nodeschool/haarlem#4]
I'm hacking on a new logo, let me know what you think.

<img width="484" alt="screen shot 2016-02-20 at 13 57 41" src="https://cloud.githubusercontent.com/assets/1814479/13196820/027bfe6c-d7da-11e5-9a7c-a251fdd131a1.png">

**Comment by codeflyer** [comment]
Why there is a "path" label in the middle?

2016-02-20 13:58 GMT+01:00 JP Wesselink notifications@github.com:

**Comment by jpwesselink** [comment]
Shouldn’t there, it’s a screen shot : )

**Comment by stefanmirck** [comment]
I like a lot. Maybe the building could be a little bit bigger as to fill out the space at the top of the octagon, i.e., the tips of the towers having the same space between the border as at the bottom? Could also make it feel too cramped or tight, but I dunno…

**Comment by stefanmirck** [comment]
Btw, are we gonna run with the abbreviation "HLM"? If so, I need to change our Twitter handle.

**Comment by jpwesselink** [comment]
'HLM'... Well. Preferably it would say `Haarlem` since that would make more sense than using a nomenclature the Dutch are not familiar with. I've been playing around with spelling out the full word. I'll show that in the next iteration.

**Comment by jpwesselink** [comment]
I tried spelling out Haarlem in full, but that yielded only tears and ugliness. s/HLM/HAR/ like it used to be. 

<img width="791" alt="screen shot 2016-02-21 at 19 01 30" src="https://cloud.githubusercontent.com/assets/1814479/13204327/9354f5c6-d8cd-11e5-998b-23d5c267d2e1.png">

**Comment by stefanmirck** [comment]
I like this iteration _a lot_! Kudos!

**Comment by jpwesselink** [comment]
Another take on the hex logo, this time in familiar yellow. 
<img width="455" alt="screen shot 2016-02-22 at 08 32 31" src="https://cloud.githubusercontent.com/assets/1814479/13212141/0006045a-d93f-11e5-8d98-67389b7e3b49.png">

**Comment by codeflyer** [comment]
I like this one!! the yellow.

2016-02-22 8:34 GMT+01:00 JP Wesselink notifications@github.com:

**Comment by jpwesselink** [comment]
Thanks :) It needs clouds I think

**Comment by jpwesselink** [comment]
I tried clouds, but that did not add anything substantially. I applied the logo.js colors. 
AFAIC this can be final.

![nodeschool-haarlem-hex-yellow](https://cloud.githubusercontent.com/assets/1814479/13225579/bfa2389e-d98d-11e5-9799-30f35a8f2725.png)

**Comment by jpwesselink** [comment]
Resolved by https://github.com/nodeschool/haarlem/commit/eeb9f68f0bb764b99c7ec8cc53ecc31e4b38cfa6

**Comment by fruitl00p** [comment]
@jpwesselink I'd respectfully like to reopen the issue: the `nodeschool`-text seems to be a different color / `hardness` that makes it stand out from the rest of the image. 
(should be clearly visible here : https://raw.githubusercontent.com/nodeschool/haarlem/master/resources/nodeschool-haarlem.png)

Thanks!

**Comment by jpwesselink** [comment]
Thanks for pointing it out, will fix asap!

**Comment by fruitl00p** [comment]
Sjeez you're quick ;)
