### ISSUE TITLE
File uploads for flyer

### ISSUE THREAD

**Issue by jpwesselink** [nodeschool/haarlem#7]
Front: 
![nodeschool-haarlem-flyer-a5-tall-preview-front](https://cloud.githubusercontent.com/assets/1814479/15241266/1b53b640-18ef-11e6-8f71-b9a85999b98c.png)

Back: 
![nodeschool-haarlem-flyer-a5-tall-preview-back](https://cloud.githubusercontent.com/assets/1814479/15241265/1aed293e-18ef-11e6-8c64-df1f8cde0a8a.png)

![img_3178](https://cloud.githubusercontent.com/assets/1814479/15242468/a90ebdc0-18f6-11e6-9acc-9479c466166e.png)

![img_7634](https://cloud.githubusercontent.com/assets/1814479/15242591/6223690a-18f7-11e6-839b-c35bb2218244.png)

![img_7633](https://cloud.githubusercontent.com/assets/1814479/15246446/3768c9e2-190d-11e6-9bc8-1f40a293b8ee.png)

![img_7659](https://cloud.githubusercontent.com/assets/1814479/15242722/0175e42e-18f8-11e6-9afd-c80904acbfe4.png)

**Comment by iancrowther** [comment]
wow - love the yellow bg
