### ISSUE TITLE
16th meetup anniversary

### ISSUE THREAD

**Issue by jpwesselink** [nodeschool/haarlem#8]
Well, we need to celebrate this, right. So as promised. New site + sweet sixteen theme :D 

@rickheere, @stefanmirck, @lulusam, @yoshuawuyts, @watilde, @codeflyer

![screen shot 2016-06-27 at 15 12 49](https://cloud.githubusercontent.com/assets/1814479/16380843/a99b09be-3c79-11e6-99a9-3f000dfda1ae.png)

**Comment by rickheere** [comment]
This is amazing1!!

**Comment by lulusam** [comment]
ahahah I love it!!:D

Awesome job JP!

On Mon, Jun 27, 2016 at 3:08 PM, JP Wesselink notifications@github.com
wrote:

> Well, we need to celebrate this, right. So as promised. New site + sweet
> sixteen theme :D
> 
> @rickheere https://github.com/rickheere, @stefanmirck
> https://github.com/stefanmirck, @lulusam https://github.com/lulusam,
> @yoshuawuyts https://github.com/yoshuawuyts, @watilde
> https://github.com/watilde, @codeflyer https://github.com/codeflyer
> 
> [image: screen shot 2016-06-27 at 15 07 52]
> https://cloud.githubusercontent.com/assets/1814479/16380716/f2f5ce1a-3c78-11e6-80e1-49bba3fbfef0.png
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/nodeschool/haarlem/issues/8, or mute the thread
> https://github.com/notifications/unsubscribe/AMdT7f3fl7uumvkRhvSkdF2opdPp09_mks5qP8tHgaJpZM4I_E09
> .

## 

https://e17782444efabb3a352b-3f635e568a6c30e9fc72c6e0da5cac75.ssl.cf3.rackcdn.com/?email=lilystamenova&option=a
https://e17782444efabb3a352b-3f635e568a6c30e9fc72c6e0da5cac75.ssl.cf3.rackcdn.com/?email=lilystamenova&option=b

http://feedbackfruits.com/ https://www.facebook.com/FeedbackFruits
http://www.twitter.com/FeedbackFruits
http://www.linkedin.com/company/2914164?trk=tyah
http://pinterest.com/feedbackfruits
https://plus.google.com/112772779277607027708

**Comment by yoshuawuyts** [comment]
Ooooh, rad!

**Comment by watilde** [comment]
Sweeet!

**Comment by jpwesselink** [comment]
You can watch the pink madness in all its glory at http://nodeschool.io/haarlem !
